import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    paddingTop: 50,
    paddingHorizontal: 12,
  },
  header: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },
  // Agrega esto al final de styleUploadFlow.js
divider: {
  height: 1,
  backgroundColor: "#222",
},
scroll: {
  paddingHorizontal: 16,
  paddingTop: 16,
  paddingBottom: 40,
},
sectionLabel: {
  color: "#F369D6",
  fontSize: 14,
  fontFamily: "Poppins_400Regular",
  fontWeight: "700",
  letterSpacing: 1,
  marginBottom: 14,
},
// Agregar al final de styleUploadFlow.js (antes del cierre del paréntesis de StyleSheet.create)

uploadSuccessContainer: {
  flex: 1,
  justifyContent: "center",
  alignItems: "center",
  paddingHorizontal: 32,
},
uploadSuccessLogo: {
  width: 110,
  height: 110,
  marginBottom: 24,
},
uploadSuccessTitle: {
  color: "#F369D6",
  fontSize: 26,
  fontFamily: "Poppins_400Regular",
  fontWeight: "900",
  letterSpacing: 1,
  textAlign: "center",
  marginBottom: 16,
},
uploadSuccessSubtitle: {
  color: "#fff",
  fontSize: 22,
  fontFamily: "Poppins_400Regular",
  textAlign: "center",
  lineHeight: 24,
  marginBottom: 40,
},
uploadSuccessBtn: {
  backgroundColor: "#F369D6",
  paddingVertical: 16,
  paddingHorizontal: 40,
  borderRadius: 14,
  flexDirection: "row",
  alignItems: "center",
  gap: 10,
  width: "100%",
  justifyContent: "center",
},
uploadSuccessBtnText: {
  color: "#fff",
  fontSize: 16,
  fontWeight: "700",
},
uploadBox: {
  height: 300,
  backgroundColor: "#F0F0F0",
  borderRadius: 16,
  justifyContent: "center",
  alignItems: "center",
  marginBottom: 24,
  gap: 6,
},
uploadText: {
  color: "#2D6CDF",
  fontSize: 15,
  fontWeight: "700",
  fontFamily: "Poppins_400Regular",
},
uploadSub: {
  color: "#888",
  fontSize: 12,
  fontFamily: "Poppins_400Regular",
},
groupTitle: {
  color: "#fff",
  fontSize: 18,
  fontWeight: "700",
  fontFamily: "Poppins_400Regular",
  textAlign: "center",
  marginBottom: 16,
},
rowFields: {
  flexDirection: "row",
  gap: 12,
  marginBottom: 4,
},
publishBtn: {
  backgroundColor: "#2563EB",
  paddingVertical: 18,
  borderRadius: 14,
  alignItems: "center",
  marginTop: 20,
},
publishText: {
  color: "#fff",
  fontSize: 16,
  fontWeight: "700",
  fontFamily: "Poppins_400Regular",
},
  section: {
    color: "#F369D6",
    fontSize: 20,
    fontFamily: "Poppins_600SemiBold",
    marginBottom: 10,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  card: {
    width: "48%",
    backgroundColor: "#111",
    borderRadius: 12,
    marginBottom: 12,
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: 140,
  },
  badgeTop: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "#333",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  badgeTopText: {
    color: "#fff",
    fontSize: 10,
  },
  info: {
    padding: 8,
  },
  title: {
    color: "#fff",
    fontSize: 11,
  },
  user: {
    color: "#F369D6",
    fontSize: 10,
    marginTop: 2,
  },
  smallBtnDark: {
    backgroundColor: "#222",
    borderRadius: 6,
    paddingVertical: 5,
    marginTop: 5,
    alignItems: "center",
  },
  smallBtnBlue: {
    backgroundColor: "#2E7BFF",
    borderRadius: 6,
    paddingVertical: 5,
    marginTop: 5,
    alignItems: "center",
  },
  smallText: {
    color: "#fff",
    fontSize: 10,
  },
  heart: {
    position: "absolute",
    bottom: 50,
    right: 10,
    backgroundColor: "#F369D6",
    borderRadius: 20,
    padding: 6,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  categoryCard: {
    width: "48%",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#2E7BFF",
    marginBottom: 12,
  },
  categoryImage: {
    width: "100%",
    height: 110,
  },
  categoryLabel: {
    color: "#4DA3FF",
    fontSize: 11,
    padding: 6,
  },
  uploadBoxReal: {
    height: 180,
    backgroundColor: "#E5E5E5",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  uploadIcon: {
    width: 40,
    height: 40,
  },
  uploadHint: {
    color: "#888",
    fontSize: 11,
  },
  previewContainer: {
    backgroundColor: "#111",
    borderRadius: 20,
    padding: 14,
    marginTop: 10,
  },
  previewImage: {
    width: "100%",
    height: 240,
    borderRadius: 16,
  },
  counter: {
    position: "absolute",
    bottom: 10,
    left: 10,
    backgroundColor: "#000",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  counterText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  bookmarkBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#F369D6",
    width: 40,
    height: 40,
    borderRadius: 999,
    justifyContent: "center",
    alignItems: "center",
  },
  previewTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "700",
    marginTop: 18,
    lineHeight: 30,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 16,
  },
  badge: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  badgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  badgeGray: {
    backgroundColor: "#5B5B66",
  },
  badgePink: {
    backgroundColor: "#FF007F",
  },
  badgeBlue: {
    backgroundColor: "#3A35FF",
  },
  badgeGreen: {
    backgroundColor: "#17C9B2",
  },
  divider: {
    height: 1,
    backgroundColor: "#2A2A2A",
    marginVertical: 22,
  },
  sectionBox: {
    backgroundColor: "#1B1B1B",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 18,
  },
  sectionText: {
    color: "#E5E5E5",
    marginTop: 14,
    fontSize: 15,
    lineHeight: 24,
  },
  sectionMargin: {
    marginTop: 20,
  },
  confirmBtn: {
    backgroundColor: "#2E7BFF",
    paddingVertical: 18,
    borderRadius: 16,
    marginTop: 30,
    alignItems: "center",
  },
  confirmBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 18,
  },
publicationImage: {
  width: "100%",
  height: 380,
},
publicationCounter: {
  position: "absolute",
  bottom: 18,
  left: 14,
  backgroundColor: "#000",
  paddingHorizontal: 10,
  paddingVertical: 6,
  borderRadius: 999,
},
publicationCounterText: {
  color: "#fff",
  fontWeight: "700",
},
publicationBookmark: {
  position: "absolute",
  bottom: 18,
  right: 14,
  backgroundColor: "#F369D6",
  width: 42,
  height: 42,
  borderRadius: 999,
  justifyContent: "center",
  alignItems: "center",
},
publicationContent: {
  backgroundColor: "#111",
  marginTop: -10,
  borderTopLeftRadius: 22,
  borderTopRightRadius: 22,
  padding: 16,
},
publicationTitle: {
  color: "#fff",
  fontSize: 18,
  fontWeight: "700",
  lineHeight: 26,
},
publicationUserRow: {
  flexDirection: "row",
  alignItems: "center",
  marginTop: 16,
},
publicationAvatar: {
  width: 42,
  height: 42,
  borderRadius: 999,
},
publicationName: {
  color: "#fff",
  fontSize: 16,
  fontWeight: "600",
},
publicationUser: {
  color: "#8B8B8B",
  marginTop: 2,
},
matchBtn: {
  backgroundColor: "#2E7BFF",
  marginTop: 18,
  paddingVertical: 16,
  borderRadius: 14,
  alignItems: "center",
  flexDirection: "row",
  justifyContent: "center",
  gap: 8,
},
matchBtnText: {
  color: "#fff",
  fontSize: 18,
  fontWeight: "700",
},
  heartBig: {
    width: 90,
    height: 90,
  },
});